id = "hyperql"
name = "HyperQL"
version = "0.1.1"
schema_version = 1
authors = ["jarbear82"]
description = "HyperQL support for Zed"
repository = "file:///home/jarbear82/Documents/hyperql/.grammar-tmp"

[grammars.hyperql]
repository = "file:///home/jarbear82/Documents/hyperql/.grammar-tmp"
rev = "102b3de351e6274d953359e8feb14e841fff7e27"

[language_servers.hyperql]
name = "hyperql-lsp"
languages = ["HyperQL"]
